### PR TITLE
Sanitize repository

### PR DESCRIPTION
**Pull request by diogobaracho**
- Tryied to make more acceptable by removing unpleasant or undesired comments
-  Added disclaimer with package, author and more
-  Added adminhtml.xml with acl rule
-  Added phpunit ecom dev very basic test for customer register just to start unit tests

### CODE REVIEW

**Comment by kistters** [comment]
Now work it

**Comment by kistters** [comment]
thx again

**Comment by kistters** [comment]
the composer.json has a strange e-mail senhor.diogo@gmail.comn, is it correct?

**Comment by diogobaracho** [comment]
This is wrong, i intend to work on installments and i can fix that email with installments pull request

**Comment by kistters** [comment]
I find a format_number problem, in that fix already fix e-mail

**Comment by diogobaracho** [comment]
Nice! 
My correct email is senhor.diogo@gmail.com

**Pull request merged**
