### PR TITLE
Sanitize repository

### PR DESCRIPTION
**Pull request by diogobaracho**
- Tryied to make more acceptable by removing unpleasant or undesired comments
- Added disclaimer with package, author and more
- Added adminhtml.xml with acl rule
- Added phpunit ecom dev very basic test for customer register just to start unit tests

### CODE REVIEW

**Comment by kistters** [comment]
Thank you.

**Comment by diogobaracho** [comment]
:)

**Comment by kistters** [comment]
Man I do wrong thing. Lost a branch dev.

**Comment by diogobaracho** [comment]
:O

**Comment by diogobaracho** [comment]
No problem. I sent another pull request, this time for master.

**Pull request merged**
